# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Add Frequency.py
# Created on: 2014-02-10 13:53:11.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Add Frequency <GeoTweet> <GeoTweet_Frequency> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments
GeoTweet = arcpy.GetParameterAsText(0)
if GeoTweet == '#' or not GeoTweet:
    GeoTweet = "GeoTweet" # provide a default value if unspecified

GeoTweet_Frequency = arcpy.GetParameterAsText(1)
if GeoTweet_Frequency == '#' or not GeoTweet_Frequency:
    GeoTweet_Frequency = "C:\\Documents and Settings\\weiry\\My Documents\\ArcGIS\\Default.gdb\\GeoTweet_Frequency" # provide a default value if unspecified

# Local variables:
GeoTweet__2_ = GeoTweet

# Process: Add Field
arcpy.AddField_management(GeoTweet, "Count", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Frequency
arcpy.Frequency_analysis(GeoTweet__2_, GeoTweet_Frequency, "USERID", "")

