# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Ctrete Track.py
# Created on: 2014-02-10 13:52:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Ctrete Track <GeoTweets> <Track_Line> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
GeoTweets = arcpy.GetParameterAsText(0)
if GeoTweets == '#' or not GeoTweets:
    GeoTweets = "GeoTweets" # provide a default value if unspecified

Track_Line = arcpy.GetParameterAsText(1)
if Track_Line == '#' or not Track_Line:
    Track_Line = "C:\\Documents and Settings\\weiry\\My Documents\\ArcGIS\\Default.gdb\\GeoTweets_TrackIntervalsToLi" # provide a default value if unspecified

# Local variables:
GeoTweet_dbf__9_ = Track_Line
GeoTweet_dbf__12_ = GeoTweet_dbf__9_
GeoTweet_dbf__7_ = GeoTweet_dbf__12_
GeoTweet_dbf__11_ = GeoTweet_dbf__7_
GeoTweet_dbf__14_ = GeoTweet_dbf__11_
GeoTweet_dbf__13_ = GeoTweet_dbf__14_
GeoTweet_dbf__10_ = GeoTweet_dbf__13_
GeoTweet_dbf__18_ = GeoTweet_dbf__10_
GeoTweet_dbf__16_ = GeoTweet_dbf__18_
GeoTweet_dbf__15_ = GeoTweet_dbf__16_
GeoTweet_dbf__2_ = Track_Line
GeoTweet_dbf__4_ = GeoTweet_dbf__2_
GeoTweet_dbf__3_ = GeoTweet_dbf__4_
GeoTweet_dbf__5_ = GeoTweet_dbf__3_
GeoTweet_dbf__6_ = GeoTweet_dbf__5_
GeoTweet_dbf__8_ = GeoTweet_dbf__6_
GeoTweet_dbf__21_ = GeoTweet_dbf__8_
GeoTweet_dbf__20_ = GeoTweet_dbf__21_
GeoTweet_dbf__17_ = GeoTweet_dbf__20_
GeoTweet_dbf__19_ = GeoTweet_dbf__17_

# Process: Track Intervals To Line
arcpy.TrackIntervalsToLine_ta(GeoTweets, Track_Line, "Time", "USERID", "", "01033-English_(United_States)", "AM", "PM", "FEET", "Distance", "SECONDS", "Duration", "MILES_PER_HOUR", "Speed", "DEGREES", "Course")

# Process: Add Date1
arcpy.AddField_management(Track_Line, "Date1", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Date1
arcpy.CalculateField_management(GeoTweet_dbf__9_, "Date1", "!Start_Time!.split(\" \")[0]", "PYTHON", "")

# Process: Add Hour1
arcpy.AddField_management(GeoTweet_dbf__12_, "Hour1", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Hour1
arcpy.CalculateField_management(GeoTweet_dbf__7_, "Hour1", "!Start_Time!.split(\" \")[1]", "PYTHON", "")

# Process: Add Minutes1
arcpy.AddField_management(GeoTweet_dbf__11_, "Minute1", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Munites1
arcpy.CalculateField_management(GeoTweet_dbf__14_, "Minute1", "int(!Hour1!.split(\":\")[0]) * 60 + int(!Hour1!.split(\":\")[1]) ", "PYTHON", "")

# Process: Add Day1
arcpy.AddField_management(GeoTweet_dbf__13_, "Day1", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Day1
arcpy.CalculateField_management(GeoTweet_dbf__10_, "Day1", "DateDiff ( \"d\", [Date1],Now (  ) )", "VB", "")

# Process: Add Z1
arcpy.AddField_management(GeoTweet_dbf__18_, "Z1", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Z1
arcpy.CalculateField_management(GeoTweet_dbf__16_, "Z1", "float(!Day1!)/365 +  float(!Minute1!) /60/24/365", "PYTHON_9.3", "")

# Process: Add Date2
arcpy.AddField_management(Track_Line, "Date2", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Date2
arcpy.CalculateField_management(GeoTweet_dbf__2_, "Date2", "!End_Time!.split(\" \")[0]", "PYTHON", "")

# Process: Add Hour2
arcpy.AddField_management(GeoTweet_dbf__4_, "Hour2", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Hour2
arcpy.CalculateField_management(GeoTweet_dbf__3_, "Hour2", "!End_Time!.split(\" \")[1]", "PYTHON", "")

# Process: Add Minutes2
arcpy.AddField_management(GeoTweet_dbf__5_, "Minute2", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Munites2
arcpy.CalculateField_management(GeoTweet_dbf__6_, "Minute2", "int(!Hour2!.split(\":\")[0]) * 60 + int(!Hour2!.split(\":\")[1]) ", "PYTHON", "")

# Process: Add Day2
arcpy.AddField_management(GeoTweet_dbf__8_, "Day2", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Day2
arcpy.CalculateField_management(GeoTweet_dbf__21_, "Day2", "DateDiff ( \"d\", [Date2],Now (  ) )", "VB", "")

# Process: Add Z2
arcpy.AddField_management(GeoTweet_dbf__20_, "Z2", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Z2
arcpy.CalculateField_management(GeoTweet_dbf__17_, "Z2", "float(!Day2!)/365 +  float(!Minute2!) /60/24/365", "PYTHON_9.3", "")

