# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Generate Twitter.py
# Created on: 2014-02-10 13:53:27.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Generate Twitter <Tweet> <GeoTweet_dbf> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Tweet = arcpy.GetParameterAsText(0)
if Tweet == '#' or not Tweet:
    Tweet = "Tweet" # provide a default value if unspecified

GeoTweet_dbf = arcpy.GetParameterAsText(1)
if GeoTweet_dbf == '#' or not GeoTweet_dbf:
    GeoTweet_dbf = "D:\\project\\UGA\\Research\\SocialNetworkAnalysis\\Twitter\\mytwitter\\gettweet\\dist\\GeoTweet.dbf" # provide a default value if unspecified

# Local variables:
GeoTweet_dbf__2_ = GeoTweet_dbf
GeoTweet_dbf__3_ = GeoTweet_dbf__2_
GeoTweet_dbf__4_ = GeoTweet_dbf__3_
GeoTweet_dbf__5_ = GeoTweet_dbf__4_
GeoTweet_dbf__6_ = GeoTweet_dbf__5_
GeoTweet_dbf__8_ = GeoTweet_dbf__6_
GeoTweet_dbf__9_ = GeoTweet_dbf__8_
GeoTweet_dbf__12_ = GeoTweet_dbf__9_
GeoTweet_dbf__7_ = GeoTweet_dbf__12_
GeoTweet_dbf__11_ = GeoTweet_dbf__7_
GeoTweet_dbf__14_ = GeoTweet_dbf__11_
GeoTweet_dbf__13_ = GeoTweet_dbf__14_
GeoTweet_dbf__10_ = GeoTweet_dbf__13_
GeoTweet_dbf__18_ = GeoTweet_dbf__10_
GeoTweet_dbf__16_ = GeoTweet_dbf__18_
GeoTweet_dbf__15_ = GeoTweet_dbf__16_
GeoTweet_Layer = GeoTweet_dbf__15_

# Process: Select Geo Tweet
arcpy.TableSelect_analysis(Tweet, GeoTweet_dbf, "\"TWEETLAT\" <> '0.0 ' AND \"TWEETLAT\" <> '0.0'")

# Process: Add X Field
arcpy.AddField_management(GeoTweet_dbf, "X", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Add Y Field
arcpy.AddField_management(GeoTweet_dbf__2_, "Y", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate X
arcpy.CalculateField_management(GeoTweet_dbf__3_, "X", "[TWEETLON]", "VB", "")

# Process: Calculate Y
arcpy.CalculateField_management(GeoTweet_dbf__4_, "Y", "[TWEETLAT]", "VB", "")

# Process: Add Time Field
arcpy.AddField_management(GeoTweet_dbf__5_, "Time", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Time
arcpy.CalculateField_management(GeoTweet_dbf__6_, "Time", "!CHECKTIME!.split(\"-\")[0]+\"/\"+!CHECKTIME!.split(\"-\")[1]+\"/\"+!CHECKTIME!.split(\"-\")[2]+\" \"+!CHECKTIME!.split(\"-\")[3]+\":\"+!CHECKTIME!.split(\"-\")[4]", "PYTHON", "")

# Process: Add Date Field
arcpy.AddField_management(GeoTweet_dbf__8_, "Date", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Date
arcpy.CalculateField_management(GeoTweet_dbf__9_, "Date", "!Time!.split(\" \")[0]", "PYTHON", "")

# Process: Add Hour
arcpy.AddField_management(GeoTweet_dbf__12_, "Hour", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Hour
arcpy.CalculateField_management(GeoTweet_dbf__7_, "Hour", "!Time!.split(\" \")[1]", "PYTHON", "")

# Process: Add Minutes
arcpy.AddField_management(GeoTweet_dbf__11_, "Minute", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Munites
arcpy.CalculateField_management(GeoTweet_dbf__14_, "Minute", "int(!Hour!.split(\":\")[0]) * 60 + int(!Hour!.split(\":\")[1]) ", "PYTHON", "")

# Process: Add Day
arcpy.AddField_management(GeoTweet_dbf__13_, "Day", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Day
arcpy.CalculateField_management(GeoTweet_dbf__10_, "Day", "DateDiff ( \"d\", [Date],Now (  ) )", "VB", "")

# Process: Add Z
arcpy.AddField_management(GeoTweet_dbf__18_, "Z", "DOUBLE", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Z
arcpy.CalculateField_management(GeoTweet_dbf__16_, "Z", "float(!Day!)/365 +  float(!Minute!) /60/24/365", "PYTHON_9.3", "")

# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management(GeoTweet_dbf__15_, "x", "y", GeoTweet_Layer, "", "Z")

