# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# clean.py
# Created on: 2014-07-23 16:13:22.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: clean <map> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

from datetime import datetime

# Script arguments
map = arcpy.GetParameterAsText(0)
scale = arcpy.GetParameterAsText(1)

def timediff(inputfield,targetfield):
	fields = (inputfield, targetfield)

	# Create update cursor for feature class 
	#
	with arcpy.da.UpdateCursor(map, fields) as cursor:

		for row in cursor:
			row[0] = ( datetime.now()-row[1] ).total_seconds()/float(scale)


			# Update the cursor with the updated list
			#
			cursor.updateRow(row)
# Process: pm25v
arcpy.AddField_management(map, "timediff", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
timediff("timediff","CheckTime")
