# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# clean.py
# Created on: 2014-07-23 16:13:22.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: clean <map> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
map = arcpy.GetParameterAsText(0)

def clean(inputfield,targetfield):
	fields = (inputfield, targetfield)
	arcpy.SetProgressorLabel("Calculating field "+ inputfield)

	# Create update cursor for feature class 
	#
	with arcpy.da.UpdateCursor(map, fields) as cursor:

		for row in cursor:
			try:
				row[0] = float(row[1])
			except:
				row[0] = -99.00000

			# Update the cursor with the updated list
			#
			cursor.updateRow(row)
	arcpy.SetProgressorPosition()
arcpy.SetProgressor("step", "Cleaning value",0, 18, 1)
# Process: pm25v
arcpy.AddField_management(map, "pm25v", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
clean("pm25v","Pm25")

# Process: pm25_24v
arcpy.AddField_management(map, "pm25_24v", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
clean("pm25_24v","Pm25_24")

# Process: so2IAQIv
arcpy.AddField_management(map, "so2IAQIv", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (4)
clean("so2IAQIv","So2IAQI")

# Process: pm25IAQIv
arcpy.AddField_management(map, "pm25IAQIv", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (5)
clean("pm25IAQIv","Pm25IAQI")

# Process: so2_24v
arcpy.AddField_management(map, "so2_24v", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (6)
clean("so2_24v","So2_24")

# Process: pm10v
arcpy.AddField_management(map, "pm10v", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (7)
clean("pm10v","Pm10")

# Process: so2v
arcpy.AddField_management(map, "so2v", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (8)
clean("so2v","So2")

# Process: pm10_24v
arcpy.AddField_management(map, "pm10_24v", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (9)
clean("pm10_24v","Pm10_24")

# Process: pm10IAQIv
arcpy.AddField_management(map, "pm10_IAQIv", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (10)
clean("pm10_IAQIv","Pm10IAQI")

# Process: no2IAQIv
arcpy.AddField_management(map, "no2IAQIv", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
clean("no2IAQIv","No2IAQI")

# Process: no2v
arcpy.AddField_management(map, "no2v", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (11)
clean("no2v","No2")

# Process: no2_24v
arcpy.AddField_management(map, "no2_24v", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (12)
clean("no2_24v","No2_24")

# Process: o3v
arcpy.AddField_management(map, "o3v", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (13)
clean("o3v","O3")

# Process: o3_24v
arcpy.AddField_management(map, "o3_24v", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (14)
clean("o3_24v","O3_24")


# Process: o3IAQIv
arcpy.AddField_management(map, "o3IAQIv", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (15)
clean("o3IAQIv","O3IAQI")

# Process: cov
arcpy.AddField_management(map, "cov", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (16)
clean("cov","Co")

# Process: coIAQIv
arcpy.AddField_management(map, "coIAQIv", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (17)
clean("coIAQIv","CoIAQI")

# Process: co_24v
arcpy.AddField_management(map, "co_24v", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (18)
clean("co_24v","Co_24")

arcpy.ResetProgressor()