# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# calculatexy.py
# Created on: 2014-07-22 17:07:58.00000
#   (generated by Xuebin Wei)
# Description: 
# ---------------------------------------------------------------------------

import arcpy

md = arcpy.GetParameterAsText(0)
arcpy.env.workspace = md
tables = arcpy.ListTables()

arcpy.SetProgressor("step", "Adding X,Y to table...",0, 35, 1)

for table in tables:
	arcpy.SetProgressorLabel("Calculating table "+ str(table))
	if table == "aotizhongxin":
		x = 116.395001
		y = 39.985994
	elif table == "dingling":
		x = 116.24608
		y = 40.296149
	elif table == "changpin":
		x = 116.2264
		y = 40.224198
	elif table == "nongzhanguan":
		x = 116.464188
		y = 39.933936
	elif table == "daxing":
		x = 116.339936
		y = 39.736666
	elif table == "yufa":
		x = 116.315443
		y = 39.510456
	elif table =="dongsi":
		x = 116.417506
		y = 39.924359
	elif table =="tiantan":
		x = 116.405294
		y = 39.880336
	elif table =="donggaocun":
		x = 117.120074
		y = 40.109543
	elif table =="dongsihuan":
		x = 116.49638
		y = 39.917014
	elif table =="fangshan":
		x = 116.141331
		y = 39.736891
	elif table =="fengtaihuayuan":
		x = 116.286107
		y = 39.863301
	elif table =="yungang":
		x = 116.160372
		y = 39.810739
	elif table =="beibuxincheng":
		x = 116.179702
		y = 40.044611
	elif table =="zhiwuyuan":
		x = 116.209812
		y = 39.996603
	elif table =="wanliu":
		x = 116.297172
		y = 39.966879
	elif table =="huairou":
		x = 116.64051
		y = 40.30222
	elif table =="liulihe":
		x = 116.037934
		y = 39.607841
	elif table =="mengtougou":
		x = 116.09513
		y = 39.944216
	elif table =="miyunshuiku":
		x = 116.841281
		y = 40.472172
	elif table =="miyun":
		x = 116.840004
		y = 40.368377
	elif table =="nansanhuan":
		x = 116.407455
		y = 39.862644
	elif table =="pinggu":
		x = 117.100514
		y = 40.139668
	elif table =="qianmen":
		x = 116.404276
		y = 39.906534
	elif table =="gucheng":
		x = 116.190717
		y = 39.907401
	elif table =="shunyi":
		x = 116.640956
		y = 40.150423
	elif table =="tongzhou":
		x = 116.656441
		y = 39.909972
	elif table =="guanyuan":
		x = 116.356583
		y = 39.929254
	elif table =="wanshouxigong":
		x = 116.369883
		y = 39.877654
	elif table =="xizhibeimen":
		x = 116.36354
		y = 39.943164
	elif table =="badalin":
		x = 115.973159
		y = 40.361211
	elif table =="yanqing":
		x = 115.984964
		y = 40.458622
	elif table =="yizhuang":
		x = 116.50575
		y = 39.8009
	elif table =="yongdingmennei":
		x = 116.406442
		y = 39.880185
	elif table =="yongledian":
		x = 116.793811
		y = 39.711958
	else:
		x = 0
		y = 0
	arcpy.AddField_management(table,"Name","TEXT")
	arcpy.AddField_management(table,"X","DOUBLE")
	arcpy.AddField_management(table,"Y","DOUBLE")
	arcpy.CalculateField_management(table,"Name",'"'+str(table)+'"')
	arcpy.CalculateField_management(table,"X",x)
	arcpy.CalculateField_management(table,"Y",y)
	arcpy.SetProgressorPosition()

arcpy.ResetProgressor()